instance_create((x + random_range(-10, 10)), (y + random_range(-10, obj_controller)), obj_glassdebris)
instance_create((x + random_range(-10, 10)), (y + random_range(-10, obj_controller)), obj_glassdebris)
instance_create((x + random_range(-10, 10)), (y + random_range(-10, obj_controller)), obj_glassdebris)
instance_create((x + random_range(-10, 10)), (y + random_range(-10, obj_controller)), obj_glassdebris)
instance_create((x + random_range(-10, 10)), (y + random_range(-10, obj_controller)), obj_glassdebris)
instance_create((x + random_range(-10, 10)), (y + random_range(-10, obj_controller)), obj_glassdebris)
tile_layer_delete_at(1, x, y)
if (!audio_is_playing(sfx_break))
    audio_play_sound(sfx_break, 1, false)
