draw_set_color(c_white)
draw_set_alpha(fadealpha)
draw_rectangle(0, 0, view_xview[0], view_yview[0], false)
draw_rectangle(0, 0, (view_xview[0] + view_wview[0]), (view_yview[0] + view_hview[0]), false)
draw_set_alpha(1)
