instance_create((x + 16), (y + 50), obj_wooddebris)
instance_create((x + 16), (y + 50), obj_wooddebris)
instance_create((x + 16), (y + 50), obj_wooddebris)
instance_create((x + 16), (y + 50), obj_wooddebris)
instance_create((x + 16), (y + 50), obj_wooddebris)
instance_create((x + 16), (y + 50), obj_wooddebris)
instance_create((x + 16), (y + 50), obj_wooddebris)
instance_create((x + 16), (y + 50), obj_wooddebris)
instance_destroy()
audio_sound_gain(sfx_break, 0.7, 0)
if (!audio_is_playing(sfx_break))
    audio_play_sound(sfx_break, 1, false)
